name: Java CI

on:
  - push
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: make build
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          TEST_COVERAGE_SECRET: ${{secrets.TEST_COVERAGE_SECRET}}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
